### ISSUE TITLE
Minor error in the README

### ISSUE THREAD

**Issue by nilsmartel** [lcnr/collatz#1]
you've written:

> meaning that this sequence must either diverge to infinity or reach 1

Though there is another possibility.

There might be a sequence of numbers that repeats itself.

some numbers x1, x2, ..., xn, so that:

x2 = f(x1)
x3 = f(x2=
...
x1 = f(xn)

where f(x) = 3x + 1

**Comment by lcnr** [comment]
The whole sentence is

> My goal is to prove that no other loop is possible, meaning that this sequence must either diverge to infinity or reach 1. While experimenting with different ideas was enjoyable, this goal has not been reached.

I know that there might be other sequence repeats itself, my goal was to prove that such a sequence cannot exist, at which point the only possible options left are diverging or ending at 1.

**Comment by nilsmartel** [comment]
Now I understand this sentence more precisely. Sorry to have bothered you and have a great time
